export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '@/styles/globals.css'

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className="bg-gray-800 text-white p-4 mb-10">
        <h1 className="text-2xl font-bold">Header</h1>
      </header>
        {children}
        <footer className="bg-gray-800 text-white p-4 mt-10">
          <h1 className="text-2xl font-bold">Footer</h1>
        </footer>
        </body>
    </html>
  )
}
 